apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-kudy
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xfbq-tenant/rhtap-demo-app/hacbs-test-project-kudy@sha256:22c6525bfd313d7a54b2dbbbf4b89f2ec2aca84f5d72c51da4f37fe66ff2382f
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
