apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-kudy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-kudy
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-kudy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-kudy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-kudy
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xfbq-tenant/rhtap-demo-app/hacbs-test-project-kudy@sha256:22c6525bfd313d7a54b2dbbbf4b89f2ec2aca84f5d72c51da4f37fe66ff2382f
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
